name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: 您要为哪些平台反馈BUG?
      description: 点击下拉选择对应的平台，若均不符合请选择其他，并于下一节补充
      options:
        - 此功能与具体平台无关
        - Nintendo Switch
        - PSVita
        - PS4
        - Xbox 系列
        - Linux 桌面/掌机
        - Windows 桌面/掌机
        - macOS
        - PC 全平台 (包含 Windows, macOS, Linux)
        - 其他
      default: 0
  - type: input
    attributes:
      label: 设备的系统版本
      description: "如: Windows10 22H2、Switch 13.0.0..."
  - type: input
    attributes:
      label: CPU 型号
      description: "部分问题可能与CPU型号有关，请如实填写，游戏主机请填写主机型号"
  - type: input
    attributes:
      label: GPU 型号
      description: "部分问题可能与GPU型号有关，请如实填写，游戏主机请填写主机型号"
  - type: textarea
    validations:
      required: true
    attributes:
      label: 描述你遇到的问题
      description: 简洁地描述问题，提供问题复现步骤，如有必要可以附加截图或录屏
  - type: textarea
    attributes:
      label: 应用日志
      description: "如有必要，使用请命令行运行: `wiliwili -d -t -o log.txt`，记录问题出现时的应用日志"
      placeholder: 游戏主机出现问题，请尝试使用电脑端复现，并记录log
  - type: textarea
    attributes:
      label: 其他补充
      description: 在此处添加有关功能请求的任何其他信息、截图或视频
      placeholder: 若无请留空
  - type: checkboxes
    attributes:
      label: 问题确认
      description: 选中下方复选框，代表您已阅读过下列内容
      options:
        - label: 阅读了 [反馈问题前要做的事](https://github.com/xfangfang/wiliwili?tab=readme-ov-file#反馈问题前要做的事)
          required: true
        - label: 搜索了 [历史 issue](https://github.com/xfangfang/wiliwili/issues?q=is%3Aissue) ，并未发现相同问题
          required: true
        - label: 查看了 [应用 wiki](https://github.com/xfangfang/wiliwili/wiki)
          required: true