name: Build borealis demo

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ssh_ubuntu:
        description: 'SSH connection to Ubuntu'
        required: false
        default: 'false'
jobs:
  build-desktop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [ x86_64 ]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'xfangfang/borealis'
          ref: 'zig'
          submodules: recursive

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_ubuntu == 'true' && github.event.inputs.ssh_ubuntu  != 'false') || contains(github.event.action, 'ssh_ubuntu')

      - name: Install dependencies
        run: |
          sudo apt update -y

      - name: Build
        id: build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DPLATFORM_DESKTOP=ON \
            -DZIG_TARGET=${{ matrix.arch }}-${{ matrix.os }}-gnu
          make -C build -j$(nproc)
          mv borealis_demo borealis-${{ matrix.arch }}-${{ matrix.os }}
          echo "DEMO=borealis-${{ matrix.arch }}-${{ matrix.os }}" >> $GITHUB_OUTPUT

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.DEMO }}
          path: "${{ steps.build.outputs.DEMO }}"
