name: Build borealis demo

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ssh_ubuntu:
        description: 'SSH connection to Ubuntu'
        required: false
        default: 'false'
jobs:
  build-psv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_ubuntu == 'true' && github.event.inputs.ssh_ubuntu  != 'false') || contains(github.event.action, 'ssh_ubuntu')
      - name: Build
        run: |
          docker run --rm -v $(pwd):/src/ xfangfang/wiliwili_psv_builder:latest \
            "mv /usr/local/vitasdk/share/gcc-arm-vita-eabi/samples/hello_world/sce_sys /src/psv/ && \
             mkdir -p /src/psv/module/ && cp /usr/local/vitasdk/arm-vita-eabi/suprx/*.suprx /src/psv/module/ && \
             cmake -B build -G Ninja -DPLATFORM_PSV=ON -DUSE_SYSTEM_SDL2=ON -DCMAKE_BUILD_TYPE=Release && \
             cmake --build build"
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: borealis-psv
          path: build/*.vpk
