name: pppwn

on:
  push:
  workflow_dispatch:

jobs:
  build-mips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'xfangfang/PPPwn_cpp'
          ref: 'mips'

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Install Dependencies
        run: sudo apt-get install llvm --no-install-recommends

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_TEST=ON -DUSE_SYSTEM_PCAP=OFF -DZIG_TARGET=mips-linux-musl -DZIG_COMPILE_OPTION='-msoft-float'
          cmake --build build -t pppwn_output
          llvm-strip build/tests/pppwn_output
          upx --lzma build/tests/pppwn_output

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: mips-linux-musl
          path: build/tests/pppwn_output
